# Generated by Django 4.2.3 on 2023-07-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nftApp', '0002_userprofile_identity_testtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='identity',
        ),
    ]
